# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solver_bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'solver_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13solver_bridge.proto\x12\x0csolverbridge\"\x8d\x01\n\x13SubmitAnswerRequest\x12\x14\n\x0c\x63hallenge_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x15\n\rsolver_job_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\nerror_code\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\"9\n\x14SubmitAnswerResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2e\n\x0cSolverBridge\x12U\n\x0cSubmitAnswer\x12!.solverbridge.SubmitAnswerRequest\x1a\".solverbridge.SubmitAnswerResponseB!Z\x1fproto/solverbridge;solverbridgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solver_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037proto/solverbridge;solverbridge'
  _globals['_SUBMITANSWERREQUEST']._serialized_start=38
  _globals['_SUBMITANSWERREQUEST']._serialized_end=179
  _globals['_SUBMITANSWERRESPONSE']._serialized_start=181
  _globals['_SUBMITANSWERRESPONSE']._serialized_end=238
  _globals['_SOLVERBRIDGE']._serialized_start=240
  _globals['_SOLVERBRIDGE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
