# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import solver_bridge_pb2 as solver__bridge__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in solver_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolverBridgeStub(object):
    """Service that external (e.g., Python) solvers can use to submit answers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitAnswer = channel.unary_unary(
                '/solverbridge.SolverBridge/SubmitAnswer',
                request_serializer=solver__bridge__pb2.SubmitAnswerRequest.SerializeToString,
                response_deserializer=solver__bridge__pb2.SubmitAnswerResponse.FromString,
                _registered_method=True)


class SolverBridgeServicer(object):
    """Service that external (e.g., Python) solvers can use to submit answers.
    """

    def SubmitAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolverBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=solver__bridge__pb2.SubmitAnswerRequest.FromString,
                    response_serializer=solver__bridge__pb2.SubmitAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'solverbridge.SolverBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('solverbridge.SolverBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolverBridge(object):
    """Service that external (e.g., Python) solvers can use to submit answers.
    """

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solverbridge.SolverBridge/SubmitAnswer',
            solver__bridge__pb2.SubmitAnswerRequest.SerializeToString,
            solver__bridge__pb2.SubmitAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
