// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: solver_bridge.proto

package solverbridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolverBridge_SubmitAnswer_FullMethodName = "/solverbridge.SolverBridge/SubmitAnswer"
)

// SolverBridgeClient is the client API for SolverBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service that external (e.g., Python) solvers can use to submit answers.
type SolverBridgeClient interface {
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
}

type solverBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverBridgeClient(cc grpc.ClientConnInterface) SolverBridgeClient {
	return &solverBridgeClient{cc}
}

func (c *solverBridgeClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, SolverBridge_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverBridgeServer is the server API for SolverBridge service.
// All implementations must embed UnimplementedSolverBridgeServer
// for forward compatibility.
//
// Service that external (e.g., Python) solvers can use to submit answers.
type SolverBridgeServer interface {
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	mustEmbedUnimplementedSolverBridgeServer()
}

// UnimplementedSolverBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolverBridgeServer struct{}

func (UnimplementedSolverBridgeServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedSolverBridgeServer) mustEmbedUnimplementedSolverBridgeServer() {}
func (UnimplementedSolverBridgeServer) testEmbeddedByValue()                      {}

// UnsafeSolverBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverBridgeServer will
// result in compilation errors.
type UnsafeSolverBridgeServer interface {
	mustEmbedUnimplementedSolverBridgeServer()
}

func RegisterSolverBridgeServer(s grpc.ServiceRegistrar, srv SolverBridgeServer) {
	// If the following call pancis, it indicates UnimplementedSolverBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolverBridge_ServiceDesc, srv)
}

func _SolverBridge_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverBridgeServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverBridge_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverBridgeServer).SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolverBridge_ServiceDesc is the grpc.ServiceDesc for SolverBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolverBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solverbridge.SolverBridge",
	HandlerType: (*SolverBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAnswer",
			Handler:    _SolverBridge_SubmitAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solver_bridge.proto",
}
